### PR TITLE
Fix bug

### LINKED ISSUE #614: 在应用横屏状态时打开相簿页面显示截断
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

在应用横屏状态时，打开快照详细页面（相簿），显示截断。
图片

### Expected behavior / 预期行为

正常显示

### Actual behavior / 实际行为

显示截断

### Steps to reproduce / 复现步骤

1. 打开应用
2. 点击“快照”
3. 打开“相簿”
4. 横屏
5. 出现问题

### UI / OS

HarmonyOS

### Android Version / Android 版本

10

### Additional info / 额外信息

建议使用ScrollView

### PR DESCRIPTION
**Pull request by qhy040404**
Close #614

### CODE REVIEW

File: app/src/main/kotlin/com/absinthe/libchecker/ui/snapshot/AlbumActivity.kt [hunk 1]
```diff
@@ -80,10 +84,22 @@ class AlbumActivity : BaseActivity<ActivityAlbumBinding>() {
...
-    binding.llContainer.addView(itemTrack)
+    binding.llContainer.apply {
+      overScrollMode = RecyclerView.OVER_SCROLL_NEVER
+      adapter = this@AlbumActivity.adapter
+      layoutManager = LinearLayoutManager(context)
+      isVerticalScrollBarEnabled = false
+      clipToPadding = false
+      clipChildren = false
+      setHasFixedSize(true)
+
```
Comment (zhaobozhen) [inline app/src/main/kotlin/com/absinthe/libchecker/ui/snapshot/AlbumActivity.kt:100]: BorderRecyclerView 需要处理下 UI

https://github.com/LibChecker/LibChecker/blob/5de6eb77324688a9f2df8868fe031ae984038ece/app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/applist/AppListFragment.kt#L104

**Review by zhaobozhen — CHANGES_REQUESTED** [review]
