### PR TITLE
Fix #526

### LINKED ISSUE #526: [BUG] 统计图表元素副标题显示错误
### LibChecker version / LibChecker 版本

2.3.5(1465)

### Bug description / Bug 描述

统计图表元素中表示安卓版本的副标题有概率显示错误

### Expected behavior / 预期行为

显示正常

### Actual behavior / 实际行为

有概率显示之前点击过元素的实际安卓版本

### Steps to reproduce / 复现步骤

1.打开统计图表
2.反复点击其中元素
3.可以查看到其中副标题显示错误

### UI / OS

Pixel Experience

### Android Version / Android 版本

13

### Additional info / 额外信息

Screenshot_20221227-103412_LibChecker

可以看到某些不该出现安卓版本的地方也受到了影响
Screenshot_20221227-103435_LibChecker

### PR DESCRIPTION
**Pull request by qhy040404**
- Post `null` to `androidVersion` when type is abi or kotlin
- Wait until value has been posted to viewModel

### CODE REVIEW

File: app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/statistics/ChartFragment.kt [hunk 1]
```diff
@@ -535,16 +537,21 @@ class ChartFragment :
...
 
-    dialog = ClassifyBottomSheetDialogFragment().apply {
-      setOnDismiss {
-        this@ChartFragment.dialog = null
-        (chartView as? Chart<*>)?.highlightValue(null)
-      }
-    }.also {
-      activity?.let { activity ->
-        it.show(activity.supportFragmentManager, ClassifyBottomSheetDialogFragment::class.java.name)
+      dialog = ClassifyBottomSheetDialogFragment().apply {
```
Comment (zhaobozhen) [inline app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/statistics/ChartFragment.kt]:
``` kotlin
withContext(Dispatchers.Main) {
  activity?.let { activity ->
    dialog = ClassifyBottomSheetDialogFragment().also {
      it.setOnDismiss {
        this@ChartFragment.dialog = null
        (chartView as? Chart<*>)?.highlightValue(null)
      }
      it.show(
        activity.supportFragmentManager,
        ClassifyBottomSheetDialogFragment::class.java.name
      )
    }
  }
}
```

在主线程检查 Activity 是否有效，再创建 dialog 会好一点
