### PR TITLE
Count X86 and X86_64 in ABI chart

### LINKED ISSUE #444: [BUG] ABI图表不统计x86软件
### LibChecker version / LibChecker 版本

2.3.2.d08396fa (1403)

### Bug description / Bug 描述

arm32能正常统计

Screenshot 2022-10-04 9 32 48 PM
Screenshot 2022-10-04 9 32 36 PM

### Expected behavior / 预期行为

统计x86软件

### Actual behavior / 实际行为

不统计x86软件

### Steps to reproduce / 复现步骤

_No response_

### UI / OS

FydeOS（安卓x86）

### Android Version / Android 版本

9

### Additional info / 额外信息

_No response_

### PR DESCRIPTION
**Pull request by qhy040404**
This PR needs to be evaluated.
I found the code for the first commit, which shows that we didn't count X86 and X86_64 initially. I don't know if we should count X86.

BTW, Fix #444.

### CODE REVIEW

File: app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/statistics/ChartFragment.kt [hunk 1]
```diff
@@ -461,7 +463,7 @@ class ChartFragment :
                 getString(R.string.title_statistics_dialog),
                 getString(R.string.string_64_bit)
               )
-              filteredList?.filter { (it.abi % MULTI_ARCH) == ARMV8 }
+              filteredList?.filter { (it.abi % MULTI_ARCH) == ARMV8 || (it.abi % MULTI_ARCH) == X86_64 }
```
Comment (Goooler) [inline app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/statistics/ChartFragment.kt]:
```suggestion
              filteredList?.filter {
                val arch = it.abi % MULTI_ARCH
                arch == ARMV8 || arch == X86_64
              }
```

File: app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/statistics/ChartFragment.kt [hunk 2]
```diff
@@ -471,7 +473,7 @@ class ChartFragment :
                 getString(R.string.title_statistics_dialog),
                 getString(R.string.string_32_bit)
               )
-              filteredList?.filter { (it.abi % MULTI_ARCH) == ARMV7 || (it.abi % MULTI_ARCH) == ARMV5 }
+              filteredList?.filter { (it.abi % MULTI_ARCH) == ARMV7 || (it.abi % MULTI_ARCH) == ARMV5 || (it.abi % MULTI_ARCH) == X86 }
```
Comment (Goooler) [inline app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/statistics/ChartFragment.kt]:
```suggestion
              filteredList?.filter {
                val arch = it.abi % MULTI_ARCH
                arch == ARMV7 || arch == ARMV5 || arch == X86
              }
```

**Comment by zhaobozhen** [comment]
Yes, I forgot to count the x86 architecture before.
